### PR TITLE
updating link to PDF, minor edits

### PR DESCRIPTION
**Pull request by joemcl**
Updated the link to the `understanding geocoder results` PDF file. Other minor edits.

### CODE REVIEW

**Comment by KarinG** [comment]
Thanks @joemcl for tidying things up.

**Comment by joemcl** [comment]
@KarinG you're welcome! BTW - does the extension also add BC ridings/constituencies/electoral districts to an address? Don't think so, from looking at the PDF of available data via the API. Just want to confirm that.

**Comment by KarinG** [comment]
No - for that we use OpenNorth.

**Comment by joemcl** [comment]
> No - for that we use OpenNorth.

OK cool, thanks - figured that was the case.

**Pull request merged**
